name: sindy
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.0
  - scipy==1.7.3
  - numpy==1.21.4
  - cmake==3.21.3
  - matplotlib==3.5.1
  - h5py==3.6.0
  - yapf==0.31.0
  - opencv==4.5.3
  - tqdm==4.62.3
  - pylint==2.12.2
  - jupyter==1.0.0
  - pip==21.3.1
  - pip:
      - pysindy==1.5.1
